### ISSUE TITLE
Update unit tests

### ISSUE THREAD

**Issue by KeenanRileyFaulkner** [byuccl/bfasst#389]
* Files in `test/` dir need to be updated to ensure coverage of recently added flows
* Considerations may need to be made for runtime on some of them
* Perhaps the ones that check ninja rebuilding could be separated so they are only run as desired
* We could also combine the `test/` and `tests/` directories safely, and eliminate old yaml files that have become legacy/unrunable
* Remove `ci/` folder from the project

**Comment by jgoeders** [comment]
I'm not sure I want to combine test and tests, as they mean somewhat different things.  `test` is specifically for unit tests, while `tests` because a shortened form of experiment configurations.  When I suggested the `tests` name to @yonnorc42, the closeness with `test` didn't occur to me.  We probably need a better name for these files.  `configs`?

**Comment by KeenanRileyFaulkner** [comment]
That's fine. I made the suggestion because I think the unittest module will support either test or tests as the name of the folder and those tests have also integrated into CI. But we can keep them separate and rename the one with the yaml files.

**Comment by jgoeders** [comment]
Lets move all yaml files to test/yml/* and remove the non-ci related configurations.

**Comment by yonnorc42** [comment]
@jgoeders So do you want to move all the `weeklytests` and `ci` yaml files to the `test/` directory? And then get rid of all the yaml files in `tests/` that aren't `weeklytests` or `ci`?
