### ISSUE TITLE
vivado invocation logs

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#408]
In our vivado [rules](https://github.com/byuccl/bfasst/blob/main/bfasst/tools/common/vivado_rules.ninja.mustache), the command is:

```
command = export tempjou=$$(mktemp); export templog=$$(mktemp); cd $cwd && {{ utils_path }}/retry.sh {{ vivado_path }} -mode batch -journal $$tempjou -log $$templog -source $in >&- && mv $$tempjou $journal && mv $$templog $log
```

I'm wondering why we are putting the logs in a temp directory. It's a bit annoying because you can't look at them while they are running.

Also the logs are only copied over if the tool runs correctly...

**Comment by jgoeders** [comment]
@KeenanRileyFaulkner

**Comment by KeenanRileyFaulkner** [comment]
We are doing this because we had issues at one point with multiple instances of vivado trampling each other's logs since they were all named the same thing. I don't know if that's still a problem, given the current setup of our build directory. As far as making sure they move over even if the command fails, can't we just change the last two `&&` symbols into `;`?

**Comment by jgoeders** [comment]
OK, I did some testing without making a temporary file and I didn't get any trampling, but it did create a bunch of temporary "backup" files that were annoying.  However, I found a way to disable them.  https://support.xilinx.com/s/question/0D52E00006iI3HUSA0/how-to-disable-backup-log-and-jou-files?language=en_US

**Comment by KeenanRileyFaulkner** [comment]
The link above seems to suggest that you just disable the logs from being created at all? Or are you referring to the comment about setting the parameter to 0 in the init tcl file?

**Comment by KeenanRileyFaulkner** [comment]
Where is the init tcl file created?

**Comment by jgoeders** [comment]
You have to create it yourself in `$HOME/.Xilinx/Vivado/init.tcl`

**Comment by KeenanRileyFaulkner** [comment]
Oh, ok. Now that I think about it, this is probably the main reason we were using temp files for the logs and moving them. I can just revert that, though, and the user can turn the backup files off on their own.

**Comment by KeenanRileyFaulkner** [comment]
An alternative to this is to change the `&&` chains on the vivado rule to `;`. This would make it so that the log is still created as a temp file, but is moved over to the correct location even if the tool fails. You still wouldn't be able to watch the log as it is written, but you also would not have to deal with backup logs.
